apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
data:
  APP_ENV: "production"
  WELCOME_MSG: "Hello from ConfigMap"

---
apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
type: Opaque
stringData:
  DB_USER: admin
  DB_PASS: s3cr3t

---
apiVersion: v1
kind: Pod
metadata:
  name: config-secret-demo
spec:
  containers:
    - name: tester
      image: busybox
      command: ["sh","-c","echo Config APP_ENV=$APP_ENV; echo Secret user from secret: $DB_USER; cat /etc/config/WELCOME_MSG; sleep 3600"]
      env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: demo-config
              key: APP_ENV
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: DB_USER
      volumeMounts:
        - name: cfg
          mountPath: /etc/config
        - name: sec
          mountPath: /etc/secret
          readOnly: true
  volumes:
    - name: cfg
      configMap:
        name: demo-config
    - name: sec
      secret:
        secretName: demo-secret